### PR TITLE
Allow command line arguments on the image

### PR DESCRIPTION
**Pull request by devinsba**
This supports setting the number of spans ala `--max-spans=N` when launching the docker container

Reported in gitter by @ostera

### CODE REVIEW

**Comment by anuraaga** [comment]
@adriancole can confirm, but if I'm not mistaken, we intentionally prefer users to use environment variables for configuration to decouple configuration of zipkin server from config file format / argument parsing. 

Should we instead (or at least in addition) add an environment variable knob here?

https://github.com/openzipkin/zipkin/blob/38720bcab29010e38fdb763d31d6768a43fac334/zipkin-server/src/main/resources/zipkin-server-shared.yml#L85

**Comment by devinsba** [comment]
Yeah, that makes sense. I was looking shortest route honestly since modifying that file in zipkin will require a release but I'm open to either

**Comment by adriancole** [comment]
I don't think we have any args that can't be converted to system parameters.. maybe we should put an example of changing the span count, just to remind folks what JAVA_OPTS is for?

**Comment by adriancole** [comment]
actually we should probably map the in-mem param to an ENV variable anyway, to clarify what is supported vs undocumented. Usually our primary things are mapped to ENV

**Comment by anuraaga** [comment]
Sounds like all of us forgot about JAVA_OPTS, example sounds good :)

**Comment by devinsba** [comment]
Yup, closing in favor of the env variable PR and hopefully one to add docs about javadoc

**Pull request closed without merging**
