### PR TITLE
Update MAINTAINER entries to OpenZipkin

### PR DESCRIPTION
**Pull request by abesto**

### CODE REVIEW

**Comment by jamescway** [comment]
this one looks iffy  :wink:  :+1:

**Comment by abesto** [comment]
Full disclosure: I had to look up "iffy". AFAICT it means "uncertain". What do you feel uncertain about here?

**Comment by jamescway** [comment]
sorry it was a joke, looks like very un-funny. :(

**Comment by abesto** [comment]
Is fine, probably just me being not a native speaker :)

Thanks for the quick review!

**Pull request merged**
