### PR TITLE
Enables tracing of zipkin-web and zipkin-query

### PR DESCRIPTION
**Pull request by adriancole**
screen shot 2015-09-16 at 1 17 23 pm

cc @kristofa

### CODE REVIEW

**Comment by yurishkuro** [comment]
the spans appear to be in the wrong order - why would getServiceNames be the last?

Cool thing though, zipkin tracing itself :+1:

**Comment by eirslett** [comment]
We still need to trace the calls to Cassandra!

**Comment by yurishkuro** [comment]
I am assuming you're still talking about client-side tracing in query service. Would be even more interesting to trace sr/ss on Cassandra, it seems to support it by including trace info in the results: http://docs.datastax.com/en/developer/java-driver/2.0/java-driver/tracing_t.html

**Comment by adriancole** [comment]
@yurishkuro wanna give it a try? Now that tracing works, shouldn't be too hard to test.

**Comment by yurishkuro** [comment]
unfortunately, we don't yet have a Java client to our tracing collectors. It should be available in a couple of weeks, then we can try plugging it in.

**Comment by eirslett** [comment]
Wow, that would be sweet to trace!

**Comment by yurishkuro** [comment]
So I had experimented with Cassandra tracing. The list of "events" Cassandra's `QueryTrace` returns does not quite map to the concept of spans, they are more like random sequential points on a single span. Plus, they are already stored in `system_traces` key space. So I decided not to write all the code to map those events into Annotations. Instead, I just attached the C* `trace id` as a binary annotation to the span, this way it can be used to retrieve the events from Cassandra. One enhancement we might put in is a notion of custom "handlers" for certain binary annotations in the UI, so that the trace id would be clickable in the span popup, and would load events from C*.

screen shot 2015-09-18 at 12 01 07 am

**Pull request merged**
