### PR TITLE
Unzip fix

### PR DESCRIPTION
**Pull request by zeagord**
Removed the unzip command and executing directly from the jar

### CODE REVIEW

**Comment by devinsba** [comment]
Unfortunately this will break the way we extend this image in `docker-zipkin-aws`, `docker-zipkin-azure`, and `docker-zipkin-gcp`

**Comment by zeagord** [comment]
Looks like I opened a can of worms. Please reject, I will check for an
alternative way.

**Comment by adriancole** [comment]
thanks for the attempt!

**Comment by adriancole** [comment]
PS https://github.com/openzipkin/zipkin-layout-factory needs an owner. This
is the biggest reason we aren't on boot 2 yet

**Pull request closed without merging**
