### PR TITLE
Added redis profile to base image

### LINKED ISSUE #77: Zipkin-query fails to start with Redis as storage
`.redis_profile` is missing from the Zipkin-base image. Startup fails when Zipkin-query tries to source the file in `run.sh`

### PR DESCRIPTION
**Pull request by skstronghold**
FIxes #77

### CODE REVIEW

**Comment by adriancole** [comment]
great! thanks for the help.

**Comment by adriancole** [comment]
heya. ps watch https://github.com/openzipkin/zipkin-redis as I'm extracting redis to its own repo. If you are interested in contributing or consuming for that matter. cc @gneokleo

**Comment by adriancole** [comment]
pps re-pushing 1.25.3 to include your changes https://travis-ci.org/openzipkin/docker-zipkin/builds/96689603

**Comment by gneokleo** [comment]
Thanks @adriancole One of the things I wanted to do was some sort of retry policy on failure. I'll try and find some time and implement it.

**Pull request merged**
