### PR TITLE
Include kafka10 collector in zipkin image and supporting changes

### PR DESCRIPTION
**Pull request by dgrabows**
These changes are an initial attempt to integrate the kafka10 collector (see https://github.com/openzipkin/zipkin/pull/1586) into the openzipkin/zipkin-kafka image. I expect this will go through significant revisions before it can be accepted, or it may just be a good discussion point that spawns one or more alternative PRs that replace it.

Currently, I am able to successfully run `docker-compose -f docker-compose.yml -f docker-compose-kafka10.yml up` (or `docker-compose -f docker-compose-mem.yml -f docker-compose-kafka10.yml up` for in-memory storage), publish span data to kafka from outside of docker, and have that data successfully successfully stored by the kafka10 collector.

The one caveat is that I've needed to add an entry to /etc/hosts on my machine in order to allow clients outside of docker to connect to Kafka. I have been using Docker for Mac for this testing, but, as I'm writing this, I'm coming to the conclusion that I should just use docker-machine instead of the docker host that Docker for Mac starts by default.

# Changes

## Update Kafka in openzipkin/zipkin-kafka

Previously, this container was Kafka 0.9.0.1 and Kafka 0.10+ is required to test the new collector. Since the sender and collector based on the the 0.8 Kafka client libraries should be compatible with 0.10+ brokers, I chose to update the current zipkin-kafka image. I also see an argument for creating a separate zipkin-kafka10 image and leaving zipkin-kafka on 0.9 if there is a desire to easily test compatibility with both versions of Kafka. The new versions being used are Kafka 0.10.2.1 and Zookeeper 3.4.9.

The 0.8 sender and collector have not been tested against the updated version of zipkin-kafka.

One thing I struggled with was finding a hostname or IP address Kafka can advertise to clients that is accessible from both inside other containers and from services reporting trace data from my machine, but outside of docker. I have it working with a local /etc/hosts entry for kafka-zookeeper but that does not seem like a good solution. I'm going to switch to testing using docker-machine, instead of using the default docker host run by Docker for Mac, and restore the KAFKA_ADVERTISED_HOST_NAME environment variable to see if that improves the situation. Docker for Mac does not appear to make the docker host accessible on a consistent IP (i.e. 192.168.99.100) the way docker-machine does, and this has led to a lot of my struggles.

## Add kafka10 collector to openzipkin/zipkin

Currently, there is an exploded version of kafka 0.10 collector autoconfigure module jar in the source for openzipkin/zipkin that gets copied into the container image. Once that artifact has been released to generally available repository somewhere, this can be switched to download the artifact from there, similar to the zipkin-server executable jar. Everything added under zipkin/zipkin/collector-kafka10-module/ can be removed once this happens.

Zipkin server is now executed with PropertiesLauncher, instead of JarLauncher. This allows for external modules, like the kafka10 collector, to be loaded conditionally using command line arguments. There are also new environment variables for setting the loader path and spring profiles to activate. When the KAFKA_BOOSTRAP_SERVERS environment variable is set, these values are updated by executing .kafka10_profile to activate the kafka10 collector.

There is a new docker-compose-kafka10.yml that can be used to include the Kafka container and activate the kafka10 collector by running `docker-compose -f docker-compose.yml -f docker-compose-kafka10.yml up`.

## Misc. Changes

I added docker-compose-mem.yml as an alternative base config to docker-compose.yml for lightweight testing with in-memory storage and no dependencies job. I did this mainly to cut down on overhead while testing changes with the zipkin and kafka containers. It doesn't need to make it into any final changes.

# Known work still to do
- [ ] Add a mechanism for overriding Kafka consumer config properties when using openzipkin/zipkin.
- [x] Pull zipkin-autoconfigure-collector-kafka10-x.x.x-module.jar from a repository, instead of including contents in project.
- [x] Restore the KAFKA_ADVERTISED_HOST_NAME environment variable for the openzipkin/zipkin-kafka image.
- [ ] Add some documentation about usage with docker-machine versus Docker for Mac, including limitations when running Kafka in a container.

### CODE REVIEW

**Comment by StephenWithPH** [comment]
@dgrabows here are my thoughts as a Zipkin user with a Kafka cluster who does lots in Docker:

- since the openzipkin/zipkin-kafka image is [not meant for production](https://github.com/openzipkin/docker-zipkin#regarding-production-usage), requiring users to manually set `KAFKA_ADVERTISED_HOST_NAME` seems acceptable to me; this is a [common problem](https://hub.docker.com/r/wurstmeister/kafka/) with Kafka in Docker, and any magic will be brittle due to OSX/*nix/Windows host differences.

- since Kafka 0.10.2 brokers [are backwards-compatible](https://kafka.apache.org/documentation/#upgrade) down to 0.8.x clients (producers and consumers), I think keeping two zipkin-kafka versions for different broker versions is overkill. Upgrading zipkin-kafka to 0.10.2 as you did seems best.

Thank you again for your hard work.

**Comment by adriancole** [comment]
next step is to rework this over the newly released 1.26.0 version of zipkin. If manual builds work pulling from a real repository, this can be merged, then a version here cut for 1.26.0

**Comment by adriancole** [comment]
I think it best to start very simple on this, as we can always rev the image (and don't want to block releases of zipkin).

I'll push a commit to squash some of the indirection, which I believe will make this look the same as those in docker-zipkin-aws and -azure. Then, we can refactor to make more fancy

**Comment by adriancole** [comment]
Note: KAFKA_ADVERTISED_HOST_NAME  needs to be an IP address or hostname that can be accessed from both inside the docker containers and and clients outside of docker that need to connect to Kafka. If using docker-machine, this value is likely 192.168.99.100 and the docker-compose configuration files for both kafka collector variants make this assumption.

**Pull request merged**
