### PR TITLE
Allow passing ES_AWS_DOMAIN via docker

### PR DESCRIPTION
**Pull request by sethp-jive**
Changes the test to allow ES_AWS_DOMAIN in addition to ES_HOSTS.

### CODE REVIEW

**Comment by adriancole** [comment]
should we also allow ES_AWS_REGION?

**Comment by adriancole** [comment]
I'll update the README. no worries

**Comment by adriancole** [comment]
Thanks for this. will re-push the tag to include this, then test it later cc @devinsba

**Comment by sethp-jive** [comment]
Ah, sorry I missed the README (the perils of editing code through a browser, I suppose). Thanks for the help!

**Comment by adriancole** [comment]
No problem!

**Pull request merged**
