### PR TITLE
Adds zipkin-ui image using NGINX

### PR DESCRIPTION
**Pull request by adriancole**
This container doubles as a skeleton for creating proxy configuration around
Zipkin like authentication, dealing with CORS with zipkin-js apps, or
terminating SSL.

It can also be adapted to test new UIs, such as https://github.com/openzipkin/zipkin-ui

Related issues which having an example NGINX config could help with:

See https://github.com/openzipkin/zipkin/issues/782
See https://github.com/openzipkin/zipkin/issues/1135
See https://github.com/openzipkin/zipkin/issues/1171
See https://github.com/openzipkin/zipkin/issues/974

### CODE REVIEW

**Comment by adriancole** [comment]
Thanks to @gena01 for the bootstrapping help!

**Comment by adriancole** [comment]
@dominikh this might be interesting to you, since you have an alternate api server that presents the zipkin api

**Comment by adriancole** [comment]
@rogeralsing once the experimental new [zipkin-ui](https://github.com/openzipkin/zipkin-ui) packaging is ready, we can bolt it onto existing zipkin installs with something like this.

screen shot 2016-09-16 at 6 59 09 pm


cc @jcarres-mdsol @prat0318 @shalako (folks who might not have seen the new UI, yet)

**Comment by adriancole** [comment]
gonna move this to a new repo "docker-zipkin-ui" since I think it adds more value coupled to that.

**Comment by jcarres-mdsol** [comment]
Looks cool!
So new deployments will need three different containers ? Zipkin, zipkin-ui , zipkin-dependencies?

**Comment by adriancole** [comment]
> Looks cool!
> So new deployments will need three different containers ? Zipkin,
> zipkin-ui , zipkin-dependencies?
>
once zipkin-ui is finished, we can make it the default javascript in
"zipkin", so probably won't need another container unless someone wants to
front with nginx for other reasons.

zipkin-dependencies definitely needs to be a separate container as seems
people need 4GB or so to execute the thing.

**Comment by jcarres-mdsol** [comment]
Cool, simpler deployments

**Comment by adriancole** [comment]
incidentally, the experimental ui could be a simple layer on the "zipkin" image, overwriting the path of the old javascript. nginx is used here to show how to do a proxy and also facilitate testing the new ui without changing the old one

**Comment by adriancole** [comment]
got a nudge that I should merge this :) I'll rename it to zipkin-ui and do that. we can always spin it out into a new repo once the new zipkin-ui progresses to the point where we can package it.

**Comment by adriancole** [comment]
done and pushed

**Pull request merged**
