### PR TITLE
Propagate SIGTERM to Java in Dockerfiles

### PR DESCRIPTION
**Pull request by 7fELF**
Allow Zipkin to quickly stop in docker-compose by propagating signals to Java.
The signal was sent to bash and ignored.

### CODE REVIEW

**Comment by adriancole** [comment]
you mind quickly checking the other docker files (to ensure no follow-up whack-a-mole changes that do the same?)

Regardless, thanks!

**Comment by 7fELF** [comment]
@adriancole I fixed every Dockerfile (c6de3d7) except Mysql because `mysqld_safe` seems to ignore SIGTERMs.

**Comment by devinsba** [comment]
Can you verify that your fix also works for zipkin-aws and zipkin-azure
images?

On Fri, Nov 17, 2017 at 12:06 PM, Antoine Baudrand <notifications@github.com

**Comment by 7fELF** [comment]
@devinsba The fix won't affect them because the Dokerfiles of zipkin-aws and zipkin-azure are overriding the `CMD` I changed.  I just checked, both images build and start correctly, but their Dockerfiles has to be fixed if you want them to react to SIGTERMs.

**Comment by adriancole** [comment]
@devinsba thx for keeping an eye out! @7fELF honestly really appreciate your help here. This will go out on the next patch; sounds like we can chase up the zipkin-aws and zipkin-azure now or later.

**Pull request merged**
